var lookAtCenter  = true;
var table = [
{text: 'O', detail: '', onShown: function(){ next(1000, 25)}},
{text: 'L', detail: '', onShown: function(){currentSlide = 6;setTimeout(function(){lookAtCenter = true;  next(5000,20)},200)}},
{text: 'I', detail: '', onShown: function(){}},
{text: 'N', detail: '', onShown: function(){}},
{text: 'E', detail: '', onShown: function(){}},
{text: ' ', detail: '', onShown: function(){}},
{text: 'R', detail: '', onShown: function(){}},
{text: 'E', detail: '', onShown: function(){currentSlide = 14;setTimeout(function(){next(5000,10)},200)}},
{text: 'P', detail: '', onShown: function(){}},
{text: 'O', detail: '', onShown: function(){}},
{text: 'S', detail: '', onShown: function(){}},
{text: 'I', detail: '', onShown: function(){}},
{text: 'T', detail: '', onShown: function(){}},
{text: 'O', detail: '', onShown: function(){}},
{text: 'R', detail: '', onShown: function(){}},
{text: 'Y', detail: '', onShown: function(){
    lookAtCenter = false;
     onRandom(true); setTimeout(function(){next();},4000)
}},
{text: '', detail: '', slide: 'slide1'},
{text: '', detail: '', slide: 'slide2'},
{text: '', detail: '', slide: 'slide3'},
{text: '', detail: '', slide: 'slide4'},
{text: '', detail: '', slide: 'slide5'},
{text: '', detail: '', slide: 'slide6'},
{text: '', detail: 'Claudia', onShown: function(){   
    demo(true);
    
}},
{text: '', detail: 'Angelica' },
{text: '', detail: 'Luz Angela' },
{text: '', detail: 'Omar' },
{text: '', detail: 'Mario' },
{text: '', detail: 'Jesus' },
{text: '', detail: 'Jose' },
{text: '', detail: 'Fabricio' },
{text: '', detail: 'Angular 6' },
{text: '', detail: '.Net Core 2.0' },
{text: '', detail: 'SQL Server' },
{text: '', detail: 'FTP' },
{text: '', detail: 'ROSEN' },
{text: '', detail: 'RTRC' },
{text: '', detail: 'Creation' },
{text: '', detail: 'Online Repository' },
{text: 'T', detail: ''  },
{text: 'H', detail: '' },
{text: 'A', detail: '' },
{text: 'N', detail: '' },
{text: 'K', detail: '' },
{text: 'S', detail: '' },
{text: '!', detail: '', onShown: function(){demo(false);}},
{text: '', detail: 'Claudia'},
{text: '', detail: 'Angelica'},
{text: '', detail: 'Luz Angela'},
{text: '', detail: 'Omar'},
{text: '', detail: 'Mario'},
{text: '', detail: 'Jesus'},
{text: '', detail: 'Jose'},
{text: '', detail: 'Fabricio'},
{text: '', detail: 'Angular 6'},
{text: '', detail: '.Net Core 2.0'},
{text: '', detail: 'SQL Server'},
{text: '', detail: 'FTP'},
{text: '', detail: 'ROSEN'},
{text: '', detail: 'RTRC'},
{text: '', detail: 'Creation'},
{text: '', detail: 'Online Repository'},
{text: '', detail: 'Claudia'},
{text: '', detail: 'Angelica'},
{text: '', detail: 'Luz Angela'},
{text: '', detail: 'Omar'},
{text: '', detail: 'Mario'},
{text: '', detail: 'Jesus'},
{text: '', detail: 'Jose'},
{text: '', detail: 'Fabricio'},
{text: '', detail: 'Angular 6'},
{text: '', detail: '.Net Core 2.0'},
{text: '', detail: 'SQL Server'},
{text: '', detail: 'FTP'},
{text: '', detail: 'ROSEN'},
{text: '', detail: 'RTRC'},
{text: '', detail: 'Creation'},
{text: '', detail: 'Online Repository'},
{text: '', detail: 'Claudia'},
{text: '', detail: 'Angelica'},
{text: '', detail: 'Luz Angela'},
{text: '', detail: 'Omar'},
{text: '', detail: 'Mario'},
{text: '', detail: 'Jesus'},
{text: '', detail: 'Jose'},
{text: '', detail: 'Fabricio'},
{text: '', detail: 'Angular 6'},
{text: '', detail: '.Net Core 2.0'},
{text: '', detail: 'SQL Server'},
{text: '', detail: 'FTP'},
{text: '', detail: 'ROSEN'},
{text: '', detail: 'RTRC'},
{text: '', detail: 'Creation'},
{text: '', detail: 'Online Repository'},
{text: '', detail: 'Claudia'},
{text: '', detail: 'Angelica'},
{text: '', detail: 'Luz Angela'},
{text: '', detail: 'Omar'},
{text: '', detail: 'Mario'},
{text: '', detail: 'Jesus'},
{text: '', detail: 'Jose'},
{text: '', detail: 'Fabricio'},
{text: '', detail: 'Angular 6'},
{text: '', detail: '.Net Core 2.0'},
{text: '', detail: 'SQL Server'},
{text: '', detail: 'FTP'},
{text: '', detail: 'ROSEN'},
{text: '', detail: 'RTRC'},
{text: '', detail: 'Creation'},
{text: '', detail: 'Online Repository'},


];