
var table = [
    {text: 'OR1', detail: ''},
{text: 'OR2', detail: ''},
{text: 'OR3', detail: ''},
{text: 'OR4', detail: ''},
{text: 'OR5', detail: ''},
{text: 'OR6', detail: ''},
{text: 'OR7', detail: ''},
{text: 'OR8', detail: ''},
{text: 'OR9', detail: ''},
{text: 'OR10', detail: ''},
{text: 'OR11', detail: ''},
{text: 'OR12', detail: ''},
{text: 'OR13', detail: ''},
{text: 'OR14', detail: ''},
{text: 'OR15', detail: ''},
{text: 'OR16', detail: '', slide: 'slide1'},
{text: 'OR17', detail: ''},
{text: 'OR18', detail: ''},
{text: 'OR19', detail: ''},
{text: 'OR20', detail: ''},
{text: 'OR21', detail: ''},
{text: 'OR22', detail: ''},
{text: 'OR23', detail: ''},
{text: 'OR24', detail: ''},
{text: 'OR25', detail: '', slide: 'slide2'},
{text: 'OR26', detail: ''},
{text: 'OR27', detail: ''},
{text: 'OR28', detail: ''},
{text: 'OR29', detail: ''},
{text: 'OR30', detail: ''},
{text: 'OR31', detail: ''},
{text: 'OR32', detail: '', slide: 'slide3'},
{text: 'OR33', detail: ''},
{text: 'OR34', detail: ''},
{text: 'OR35', detail: ''},
{text: 'OR36', detail: ''},
{text: 'OR37', detail: ''},
{text: 'OR38', detail: '', slide: 'slide4'},
{text: 'OR39', detail: ''},
{text: 'OR40', detail: ''},
{text: 'OR41', detail: ''},
{text: 'OR42', detail: ''},
{text: 'OR43', detail: ''},
{text: 'OR44', detail: ''},
{text: 'OR45', detail: ''},
{text: 'OR46', detail: '', slide: 'slide5'},
{text: 'OR47', detail: ''},
{text: 'OR48', detail: ''},
{text: 'OR49', detail: ''},
{text: 'OR50', detail: ''},
{text: 'OR51', detail: ''},
{text: 'OR52', detail: ''},
{text: 'OR53', detail: ''},
{text: 'OR54', detail: ''},
{text: 'OR55', detail: ''},
{text: 'OR56', detail: ''},
{text: 'OR57', detail: ''},
{text: 'OR58', detail: ''},
{text: 'OR59', detail: ''},
{text: 'OR60', detail: '', slide: 'slide6'},
{text: 'OR61', detail: ''},
{text: 'OR62', detail: ''},
{text: 'OR63', detail: ''},
{text: 'OR64', detail: ''},
{text: 'OR65', detail: ''},
{text: 'OR66', detail: ''},
{text: 'OR67', detail: ''},
{text: 'OR68', detail: ''},
{text: 'OR69', detail: ''},
{text: 'OR70', detail: ''},
{text: 'OR71', detail: ''},
{text: 'OR72', detail: ''},
{text: 'OR73', detail: ''},
{text: 'OR74', detail: ''},
{text: 'OR75', detail: ''},
{text: 'OR76', detail: ''},
{text: 'OR77', detail: ''},
{text: 'OR78', detail: ''},
{text: 'OR79', detail: ''},
{text: 'OR80', detail: ''},


];